---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.json'
      - 'package.json'
      - 'package-lock.json'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run markdown linter
      run: npm run lint:md
